In [1]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [2]:
%cd /content/drive/MyDrive/mSHIFT_SHeS/code_ocean/

/content/drive/MyDrive/mSHIFT_SHeS/code_ocean

This notebook contains the scripts for calculating the population level impacts adjusted for daily caloric intake.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json
from pathlib import Path
import sys

data_path = Path("data")

In [4]:
# Add the parent directory of the notebook to sys.path, enables module imports from analysis_code
sys.path.append(str(Path().resolve() / 'code/notebooks/notebook_code'))

In [5]:
from population_impacts import *

In [6]:
df_baseline = pd.read_parquet(data_path / 'df_baseline.parquet')

In [7]:
df_baseline['Energykcal'].median()

1552.55

In [ ]:
#Approx for the percent level of under-reporting in SHeS 2021
1 - 1552.55/2250

0.3099777777777778

In [11]:
# calculate the individual level gap in calories
df_baseline['energy_gap'] = df_baseline.apply(lambda row: energy_gap(row), axis=1)

In [9]:
# scale the sample weights by the sample weight scale computed in NB8 - should not be needed as weights have already been scaled.
#df_baseline['Sample Weight'] *= 1325.319

In [8]:
df_baseline['Sample Weight'].head()

1400000801     412.157755
1400001201     709.159249
1400001202     802.637987
1400001301     926.674216
1400003001    1246.039019
Name: Sample Weight, dtype: float64

In [14]:
np.average(df_baseline['median_Land'], weights=df_baseline['Sample Weight'])

np.float64(5.783181071048546)

In [16]:
df_baseline.head()

,Energykcal,EnergykJ,Proteing,Fatg,Carbohydrateg,Sodiummg,Potassiummg,Calciummg,Magnesiummg,Phosphorusmg,...,median_GHG_per_kcal,energy_gap,median_GHG_adjusted,sd_median_GHG_adjusted,within_psu_variance,within_strata_variance,strata variance,median_Land_per_kcal,median_Land_adjusted,sd_median_Land_adjusted
1400000801,1436.490,6027.450,64.150,64.110,160.880,1744.450,2484.960,862.450,195.310,1016.050,...,0.003202,563.510,6.403816,0.217947,0.000000e+00,1.071217e+10,1.093815e+10,0.003344,6.688332,0.353049
1400001201,2725.115,11474.435,139.640,109.235,314.675,3317.695,4233.235,1639.160,479.355,2366.650,...,0.002349,0.000,6.400849,0.490336,1.433140e+06,4.081884e+09,4.170725e+09,0.002595,7.072281,0.545691
1400001202,1514.165,6366.145,54.100,65.715,188.670,1199.840,2276.420,555.515,302.475,1052.180,...,0.002016,485.835,4.032547,0.389915,1.433140e+06,4.081884e+09,4.170725e+09,0.002412,4.823955,0.423900
1400001301,1699.870,7158.580,54.835,61.675,245.395,2404.210,1964.075,1076.425,317.385,1343.835,...,0.001470,300.130,2.940516,0.723355,0.000000e+00,1.071217e+10,1.093815e+10,0.001902,3.803227,0.930415
1400003001,1482.500,6209.255,61.795,67.000,134.225,1694.720,2083.150,841.200,202.540,1013.975,...,0.002888,811.500,6.624873,0.581367,2.440831e+07,1.026798e+09,1.092012e+09,0.004033,9.252190,0.999303

In [20]:
env_indicator = 'median_Eut'

df_baseline = baseline_impact_adjusted(indicator=env_indicator,
                                       df_baseline=df_baseline)

population_impact = weighted_impact(variable=f'{env_indicator}_adjusted',
                                    df_baseline=df_baseline)

Weighted Sum: 40645147460.09518
95% Confidence Interval: (40115900679.9593, 41174394240.23106)

In [21]:
df_baseline['Sample Weight'].sum()

np.float64(4568374.592972169)